### ISSUE TITLE
Prometheus metrics: Do not report old data

### ISSUE THREAD

**Issue by mar-v-in** [plumpudding/hopglass-server#26]
When there is a downtime in hopglass-server, it will expose old statistics values to prometheus, resulting in wrong datasets being written to the prometheus database. You should not report statistics data if it's old, e.g. Traffic data will be completely misleading: http://i.imgur.com/lPuZhZW.png (obviously there was no jump in traffic usage, just the old value being used on the first report)

**Comment by plumpudding** [comment]
I can't confirm this. How do you query prometheus? In Grafana there is an option to fill the missing points and it is turned on by default.

**Comment by mar-v-in** [comment]
The image uploaded above was generated using the Prometheus webfrontend with the query `statistics_traffic_rx_bytes{hostname="[nodename-here]"}`. As an explanation to the image: There are no data points on the middle part (where there is no increase), but there is a data point just before the new data point. You can also see the problem in our Grafana instance at https://mgmt.saar.freifunk.net/grafana/dashboard/file/overview.json - Prometheus `rate()` function will cause a very high rate because of the jump.

I guess this might be a timing issue, I just looked through the source code and think it sort of went like this:

1. Read old data from `raw.json`
2. Requested new data
3. Prometheus reads `/metrics` which still contains data from `raw.json`
4. New data arrived

Or did I miss something there? We are running on master, 0.1rc was not there when we deployed. If you think there is something new in rc that fixes this issue, you can of course ignore this report. 

Some thought to add: when the udp packet is lost on its way to one node (which happens from time to time) the new data will arrive with a minute delay, which means that Prometheus is much more likely to catch the old state. I think you can simulate this behavior by setting a wrong `iface` before restarting the server. Also note that for results to be visible you should simulate a downtime > 5min

**Comment by plumpudding** [comment]
I don't think the rc changes anything.
Actually when the server starts up it won't deliver any data to prometheus, because all the nodes are offline.

**Comment by mar-v-in** [comment]
> Actually when the server starts up it won't deliver any data to prometheus, because all the nodes are offline.

One sidecase: https://github.com/plumpudding/hopglass-server/blob/master/hopglass-server.js#L89 will be executed also for non-statistics updates, thus when you receive nodeinfo/neighbour before statistics...

**Comment by mar-v-in** [comment]
Update: Old data is also reported when there is a bad link and thus the udp packages don't come through. This can lead to [this uptime graph](http://i.imgur.com/AWq02iY.png) which is obviously wrong as uptime can not stay the same over time.

I am working on a fix, that stores the time an update was received and uses this as a timestamp in the prometheus metrics. This means that old data will still be visible in `/metrics` but annotated with an older timestamp. Additionally this will increase performance of prometheus as old data is not stored multiple times and thus the database will be smaller.

**Comment by plumpudding** [comment]
I see the problem. So we have to decide whether the data is provided differently (have we received data in the last minute?).

**Comment by mar-v-in** [comment]
This would require prometheus to grab data once per minute, which is not necessarily the case (and should not be enforced by hopglass).
I implemented timestamped metrics in my commit 0bbd59f, but was not able to try if prometheus handles timestamped metrics as I expect it.

**Comment by plumpudding** [comment]
Done.
The time the data is valid for prometheus is configurable.
Timestamped metrics are a different issue.

**Comment by mar-v-in** [comment]
60d3652 does not solve the problem for lastseen being set due to update of `neighbours` or `nodeinfo`, without new `statistics`, this means that old data can still be reported. This happens especially when nodes have a bad connection, because this leads to high chance of statistics request/response being lost

**Comment by plumpudding** [comment]
That's right. I will implement that too.

**Comment by plumpudding** [comment]
better?

**Comment by mar-v-in** [comment]
65c00b7 looks good 👍
